
/**
 * @copyright Srdjan Stojanovic
 * @version 1.0
 * @package
 * @author Srdjan Stojanovic
 * @url srdjan.icodes.rocks
 * @gitUrl https://github.com/srkis
 * @todo
 **/


/*

****************************
*                          *
* DO NOT EDIT THIS FILE!   *
*                          *
****************************

*/



// Dobavljanje Grada i Drzave za korisnika
var city;
var country;

function userData(url)
  {

           $.ajax({
              url: "http://ip-api.com/json",
              success: function(response) {
                  getWeather(response,url);  // pozivamo funkciju on ajax success da bi joj prosledili kao parametar response

              }

              });

      }


// Prikazivanje vremenske prognoze na show_weather_widget.php

function getWeather(response, url){

    city = response.city;
    country = response.country;

    $('.city').html(city + " , " + country);

        return $.ajax({
            type: "post",
            data : {city : city},
            url: ""+url+"/wp-content/plugins/weather/api/api_call.php",

            success: function(response) {
                changeIcon(response);

                var description = response.weather[0].description;
                var temp = response.main.temp ;
                var icon = response.weather[0].icon;
                var humidity = response.main.humidity;
                var wind = response.wind.speed;
                var pressure = response.main.pressure;
                var temp_min = response.main.temp_min;
                var temp_max = response.main.temp_max;


                $('.description').html("Condition:" + " " + description);
                $('.temperature').html(Math.round(temp)+"&deg;");
                $('.weatherIcon').html("<img src='http://openweathermap.org/img/w/"+icon+".png'>");
                $('.humidity').html("Humidity: " + humidity+"%");
                $('.wind').html("Wind Speed: " + wind+"km/s");
                $('.pressure').html("Preassure: " + pressure+"Pa");
                $('.temp_min').html("Temp min: " + Math.round(temp_min)+"&deg;");
                $('.temp_max').html("Temp max: " + Math.round(temp_max)+"&deg;");


            }


        });
    }

    function changeIcon(response) {

       var description = response.weather[0].description;
       //  var description = "clear sky";
        //var description = "rain";
        var icon;
        switch(description) {
            case "clear sky":
                $(".icon1").css("display", "inline-block");
               icon =' <div class="icon1"> <div class="sun"></div></div>';
                $('div#changeIcon').append("<div style='position: absolute;'>"+icon+"</div>");
                break;

            case "scattered clouds":
                $(".icon2").css("visibility", "visible");
                icon ='<div class="icon2"> <div id="clouds"> <div class="cloud"></div> <div class="cloud cloud-gray"></div> </div> </div>';
                $('div#changeIcon').append("<div>"+icon+"</div>");
                break;

            case "few clouds":
                $(".icon3").css("visibility", "visible");
                icon ='<div class="icon3"> <div id="clouds"> <div class="cloud"></div> <div class="cloud cloud-gray"></div> </div> </div>';
                $('div#changeIcon').append("<div>"+icon+"</div>");
                break;

            case "shower rain":
                $(".icon3").css("visibility", "visible");
                icon =' <div class="icon3"><div id="drizzle"><div class="cloud"><div class="drops"></div></div></div></div>';
                $('div#changeIcon').append("<div>"+icon+"</div>");
                break;

            case "broken clouds":
                $(".icon6").css("visibility", "visible");
                icon ='<div class="icon6"><div id="thunderstorm"><div class="cloud cloud-storm"><div style="position: relative; class="thunderbolt"></div></div></div><div class="cloud cloud-gray"></div></div>';
                $('div#changeIcon').append("<div>"+icon+"</div>");

                break;
            case "rain":
                $(".icon4").css("visibility", "visible");
                icon ='<div class="icon4"> <div id="rain"><div class="cloud"> <div class="drops"></div>  <div class="drops-rain"></div> </div> </div> </div>';
                $('div#changeIcon').append("<div>"+icon+"</div>");
                break;
            case "thunderstorm":
                $(".icon6").css("visibility", "visible");
                icon ='<div class="icon6"><div id="thunderstorm"><div class="cloud cloud-storm"><div class="thunderbolt"></div> </div></div><div class="cloud cloud-gray"></div></div>';
                $('div#changeIcon').append("<div>"+icon+"</div>");
                break;
            case "snow":
                $(".icon5").css("visibility", "visible");
                icon ='<div class="icon5"> <div id="snow"><div class="cloud"><div class="snowflakes">❄</div> </div> </div> </div>';
                $('div#changeIcon').append("<div>"+icon+"</div>");
                break;
            case "mist":
                $(".icon3").css("visibility", "visible");
                icon ='<div class="icon3"> <div id="clouds"> <div class="cloud"></div> <div class="cloud cloud-gray"></div> </div> </div>';
                $('div#changeIcon').append("<div>"+icon+"</div>");
                break;
            default:
                $(".icon1").css("display", "inline-block");
                icon =' <div class="icon1"> <div class="sun"></div></div>';
                $('div#changeIcon').append("<div style='position: absolute;'>"+icon+"</div>");
        }
       return icon;
    }






function dateMonth() {

var d = new Date();
document.getElementById("weather_day").innerHTML = d.getDate();

var month = new Array();
month[0] = "January";
month[1] = "February";
month[2] = "March";
month[3] = "April";
month[4] = "May";
month[5] = "June";
month[6] = "July";
month[7] = "August";
month[8] = "September";
month[9] = "October";
month[10] = "November";
month[11] = "December";
document.getElementById("weather_month").innerHTML = month[d.getMonth()];

}
